config/routes.rb
Voting::Application.routes.draw do
  
  root 'main#index'

  devise_for :users, controllers: { registrations: "registrations" }

  devise_scope :user do
    get 'login' => 'devise/sessions#new'
    get 'join' => 'devise/registrations#new'
    get 'settings' => 'devise/registrations#edit'
  end

  resources :polls do
    get :newquestion, on: :member
  end
  
  resources :questions do
    get :upvote, on: :member
    get :revote, on: :member
  end

end

app/models/poll.rb
class Poll < ActiveRecord::Base

  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, allow_destroy: true

end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :poll
  default_scope -> { order('votes_count DESC') }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    @polls = Poll.all
  end

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :newquestion]

  def index
    @polls = Poll.all
  end
  
  def show
    @poll = Poll.find(params[:id])
  end

  def new
    @poll = Poll.new
    3.times { @poll.questions.build }
  end
  
  def create
    @poll = Poll.create(poll_params)
    if @poll.save
      redirect_to poll_path(@poll)
      flash[:succsess] = "Poll created!"
    else
      render 'new'
    end
  end

  def edit
    @poll = Poll.find(params[:id])
  end

  def update
    @poll = Poll.find(params[:id])
    @poll.update_attributes(poll_params)
    if @poll.errors.empty?
      redirect_to poll_path(@poll)
      flash[:succsess] = "Poll updated!"
    else
      render 'edit'
    end
  end

  def newquestion
    @poll = Poll.find_by(params[:poll])
    question = Question.create(title: nil, comment: nil)
    @poll.questions << question
    redirect_to :back
  end

    private

      def poll_params
        params.require(:poll).permit(:name, questions_attributes:  [:id, :title, :comment, :_destroy])
      end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :authenticate_user!

  # def new
  #   @question = Question.new
  # end

  # def create
  #   @question = Question.create(question_params)
  #   if @question.save
  #     flash[:succsess] = "Question created"
  #   else
  #     render 'new'
  #   end
  # end

  def upvote
    if session[:voted_at] == nil || session[:voted_at] < 24.hours.ago
      session[:voted_at] = nil
      session[:voted] = false
    end
    if session[:voted] == false
      @question = Question.find(params[:id])
      @question.increment!(:votes_count)
      session[:voted_id] = @question.id
      session[:voted] = true
      session[:voted_at] = Time.now
      redirect_to :back
    else
      redirect_to :back
      flash[:error] = "You have already voted today!"
    end
  end

  def revote
    @question = Question.find(session[:voted_id])
    @question.decrement!(:votes_count)
    session[:voted_at] = nil
    session[:voted] = false
    redirect_to :back
  end

  # private

  #   def question_params
  #     params.require(:question).permit(:title, :comment, :votes_count)
  #   end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
  before_filter :configure_permitted_parameters
 
  protected
 
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit(:username, :email, :password, :password_confirmation)
      end
      devise_parameter_sanitizer.for(:account_update) do |u|
        u.permit(:username,
          :email, :password, :password_confirmation, :current_password)
      end
    end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Voting
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render 'shared/alerts'
    = render 'shared/header'
    .content
      = yield

app/views/main/index.html.haml
%p= link_to 'New poll', new_poll_path, class: 'button medium rounded blue'
.medium-offset.bottom
- @polls.each do |f|
  .inline
    %h4= f.name
  .inline
    .meta.small
      %span= link_to 'Show', poll_path(f)
      %span= link_to 'Edit', edit_poll_path(f)
  - f.questions.each do |g|
    .extrasmall-offset.up
      - unless g.title == nil || g.comment == nil
        %p= g.title
        .inline
          .meta.italic
            %p= g.comment
        .inline
          - if session[:voted] == true
            .meta.border.round
              %p= g.votes_count
          - else
            %p= link_to 'Vote', upvote_question_path(g), class: 'meta underline' unless !signed_in?
  .extrasmall-offset.up
    - if session[:voted] == true
      %p= link_to 'Revote', revote_question_path(f), class: 'meta underline' unless !signed_in?
  .medium-offset.bottom

app/views/polls/edit.html.haml
.fields
  = form_for @poll do |f|
    = f.label :name
    = f.text_field :name, class: 'textform'
    .medium-offset.bottom
    
    = f.fields_for :questions do |builder|
      = builder.label :title
      %p= builder.text_field :title, class: 'textform'
      = builder.label :comment
      %p= builder.text_field :comment, class: 'textform'
      .inline
        = builder.check_box :_destroy
      .inline
        = builder.label :_destroy, "Remove"
      .small-offset.bottom
    %p= link_to 'New question', newquestion_poll_path(f)
    .small-offset.bottom
    = f.submit 'Update', class: 'button medium rounded blue'

app/views/polls/index.html.haml
- @polls.each do |f|
  - f.questions.each do |g|
    = g.title
    = g.comment
    = g.votes_count

app/views/polls/new.html.haml
.fields
  = form_for @poll do |f|
    = f.label :name
    = f.text_field :name, class: 'textform'
    .small-offset.bottom
    
    = f.fields_for :questions do |builder|
      %p= builder.text_field :title, placeholder: 'Title', class: 'textform'
      %p= builder.text_field :comment, placeholder: 'Comment', class: 'textform'
      .small-offset.bottom
    .small-offset.bottom
    = f.submit 'Create', class: 'button medium rounded blue'

app/views/polls/show.html.haml
%h4= @poll.name
.extrasmall-offset.up
- for question in @poll.questions.each
  %p= question.title
  .inline
    .meta.italic
      %p= question.comment
  .inline
    - unless question.title == nil || question.comment == nil
      - if session[:voted] == true
        .meta.border.round
          %p= question.votes_count
      - else
        %p= link_to 'Vote', upvote_question_path(question), class: 'meta underline' unless !signed_in?

app/views/questions/new.html.haml
= form_for @question do |f|
  = f.text_field :title
  = f.text_field :comment
  = f.submit
 

app/views/shared/_alerts.html.haml
- if flash[:error]
  .alert.error.center= flash[:error]
- if flash[:success]
  .alert.success.center= flash[:success]
- if flash[:warning]
  .alert.warning.center= flash[:warning]
- if flash[:notice]
  .alert.notice.center= flash[:notice]

app/views/shared/_header.html.haml
.menubar
  .content
    .left
      .navbar-element
        %h3= link_to "Voting", root_path
    .right
      - if user_signed_in?
        .navbar-element= link_to current_user.username, settings_path
        .navbar-element #{link_to "Log out", destroy_user_session_path, method: :delete}
      - else
        .navbar-element= link_to "Log in", login_path
        .navbar-element= link_to "Sign up", join_path